Regisztráció kiegészítése és szűkítése 'Admin' jogkörre
herbakmarcell/afp2_saturn pull request #118
Opened 2024-04-13 21:25 UTC by herbakmarcell

2024-04-13 21:36 UTC, gyorkistamas requested changes

2024-04-13 21:36 UTC, gyorkistamas commented on Project/ASP_Core/Database/SaturnContext.cs
> +            return searchedUser.Roles;
Ez itt ne így legyen, a felhasználó role-jait a modell-en keresztül kérjük le.

2024-04-13 21:36 UTC, gyorkistamas commented on Project/ASP_Core/Services/Auth/AuthService.cs
> +            }
Ezeket és társait esetleg nem lehetne kiszervezni a RegisterModel-hez validációként, mint  a required esetén?

2024-04-13 21:36 UTC, gyorkistamas commented on Project/ASP_Core/Services/Auth/AuthService.cs
> +            }
Ezt nem teljesen értem. Regisztrációkor megkapja az adminnak a saturn kódját, és az alapján nézi meg, hogy jogosult-e a regisztrációra? Mert ebben az esetben ezt ki kéne cserélni - ha nem is most, később is elég - , hogy csak bejelentkezett felhasználók érhessék el a regisztrációs útvonalat, ahol emg van vizsgálva, hogy a bejelentkezett személy admin-e.

2024-04-13 21:50 UTC, herbakmarcell commented on Project/ASP_Core/Services/Auth/AuthService.cs
> +            }
Javítottam.

2024-04-13 21:52 UTC, herbakmarcell commented on Project/ASP_Core/Database/SaturnContext.cs
> +            return searchedUser.Roles;
Szerintem ez nem is volt használva már, csak bent maradt, de kivettem!

2024-04-17 11:02 UTC, gyorkistamas approved these changes

2024-04-17 11:02 UTC, merged